services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Xima\XimaTypo3InternalNews\:
    resource: "../Classes/*"
    exclude: "../Classes/Domain/Model/*"

  cache.xima_typo3_internal_news_cache:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', "getCache"]
    arguments: ["xima_typo3_internal_news_cache"]

  Xima\XimaTypo3InternalNews\Service\CacheService:
    arguments:
      $cache: "@cache.xima_typo3_internal_news_cache"


  Xima\XimaTypo3InternalNews\Hooks\DataHandler:
    public: true
    arguments:
      $cache: "@cache.xima_typo3_internal_news_cache"

  Xima\XimaTypo3InternalNews\Widgets\Provider\CreateInternalNewsButtonProvider:
    arguments:
      $title: "LLL:EXT:xima_typo3_internal_news/Resources/Private/Language/locallang.xlf:widgets.internalNews.news.button.create"

  Xima\XimaTypo3InternalNews\Widgets\Provider\ListInternalNewsButtonProvider:
    arguments:
      $title: "LLL:EXT:xima_typo3_internal_news/Resources/Private/Language/locallang.xlf:widgets.internalNews.news.button.list"

  dashboard.widget.InternalNews-news:
    class: 'Xima\XimaTypo3InternalNews\Widgets\InternalNewsWidget'
    arguments:
      $dataProvider: '@Xima\XimaTypo3InternalNews\Widgets\Provider\InternalNewsDataProvider'
      $buttons:
        - '@Xima\XimaTypo3InternalNews\Widgets\Provider\CreateInternalNewsButtonProvider'
        - '@Xima\XimaTypo3InternalNews\Widgets\Provider\ListInternalNewsButtonProvider'
      $options:
        refreshAvailable: true
    tags:
      - name: dashboard.widget
        identifier: "internalNews-news"
        groupNames: "news"
        title: "LLL:EXT:xima_typo3_internal_news/Resources/Private/Language/locallang.xlf:widgets.internalNews.news.title"
        description: "LLL:EXT:xima_typo3_internal_news/Resources/Private/Language/locallang.xlf:widgets.internalNews.news.description"
        iconIdentifier: "internal-news-news-color"
        height: "medium"
