type: php
docroot: .Build
additional_hostnames:
  - 11.xima-typo3-internal-news
  - 12.xima-typo3-internal-news
  - 13.xima-typo3-internal-news
hooks:
   post-start:
    - exec: mkdir -p /var/www/html/.Build/ && cp /var/www/html/.ddev/.typo3-setup/templates/* /var/www/html/.Build/
