type: php
docroot: .Build
webserver_type: apache-fpm
additional_hostnames:
  - 13.xima-typo3-internal-news
  - 14.xima-typo3-internal-news
hooks:
   post-start:
    - exec: mkdir -p /var/www/html/.Build/ && cp /var/www/html/.ddev/.setup/templates/* /var/www/html/.Build/
